name: ada chatgpt workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Set the Node.js environment variable
      run: echo "NODE_ENV=production" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Install dependencies
      run: npm install

    - name: Install pa11y-ci globally
      run: npm install -g pa11y-ci

    - name: Run ADA compliance check
      run: npm run ada-check || true

    - name: Run ADA compliance checks and save the report
      run: npx pa11y-ci > ada-report.txt || true

    - name: Send ADA report via email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ADA Report for my website.
        body: The attached file contains the ADA compliance report.
        to: recipient@example.com
        from: sender@example.com
        content_type: text/plain
        attachments: ada-report.txt
