name: ADA Compliance Check and Email

on: [push]

jobs:
  ada_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Create run_pa11y.sh script
      run: |
        echo '#!/bin/bash' > run_pa11y.sh
        echo 'set -o pipefail' >> run_pa11y.sh
        echo 'npx pa11y-ci --config .pa11yci.json --json > ada-report.txt' >> run_pa11y.sh
        chmod +x run_pa11y.sh

    - name: Run ADA compliance checks and save the report
      run: ./run_pa11y.sh || true

    - name: Send email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ADA Compliance Report
        body: Read the attached file for the full ADA compliance report.
        to: ${{ secrets.EMAIL_USERNAME }}
        from: ${{ secrets.EMAIL_USERNAME }}
        content_type: text/plain
        attachments: ada-report.txt
