name: ADA Compliance Check and Email

on: [push]

jobs:
  ada_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run ADA compliance checks and save the report
      run: |
        touch ada-report.txt
        npx pa11y-ci --config .pa11yci.json > ada-report.txt 2>&1 || true

    - name: Send email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ADA Compliance Report
        body: Read the attached file for the full ADA compliance report.
        to: your_email@example.com
        from: Your Name <your_email@example.com>
        content_type: text/plain
        attachments: ada-report.txt

