name: ada chatgpt workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Set the Node.js environment variable
      run: echo "NODE_ENV=production" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: Install dependencies
      run: npm install
    - name: Run ADA compliance check
      run: npm run ada-check

    - name: Run ADA compliance checks
      run: npx pa11y-ci > ada-report.txt

    - name: Send ADA report to ChatGPT
      run: |
        curl -X POST https://api.openai.com/v1/engines/davinci-codex/completions \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ secrets.CHATGPT_API }}" \
        --data '{"prompt": "ADA report:\n\n'$(cat ada-report.txt)'", "max_tokens": 5, "n": 1, "stop": null, "temperature": 0.7}'

